# docker compose --env-file ../../.env up --build
services:
  
  api:
    build:
      context: ../../                
      dockerfile: environments/dev/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Server=${POSTGRES_SERVER};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
    # Avoid IDE reference issues for hot reload by separating volumes
    # Mount each source folder separately
    - ../../API:/src/API
    - ../../Application:/src/Application
    - ../../Domain:/src/Domain
    - ../../Persistence:/src/Persistence
    # Isolate bin/obj for each project
    - /src/API/bin
    - /src/API/obj
    - /src/Application/bin
    - /src/Application/obj
    - /src/Domain/bin
    - /src/Domain/obj
    - /src/Persistence/bin
    - /src/Persistence/obj
    working_dir: /src/API
    env_file:
      - ../../.env
    depends_on:
      - db
    restart: always
    command: dotnet watch --no-hot-reload --project API.csproj run --urls=http://0.0.0.0:5000

  client:
    build:
      context: ../../
      dockerfile: environments/dev/Dockerfile.Client
    ports:
      - "8081:3000"
    volumes:
      - ../../client:/src
      - /src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    working_dir: /src
    command: npm run dev # because using vite
    depends_on:
      - api
      - db
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ../../.env
    volumes:
      - eventsapp_data:/var/lib/postgresql
      


        
volumes:
  eventsapp_data: